### ISSUE TITLE
Client fails with segmentation violation

### ISSUE THREAD

**Issue by jojomi** [alexellis/inlets#51]
I can't connect with a client.

## Expected Behaviour
Connection should be opened.

## Current Behaviour
```
inlets client --remote mydomain.com:8000 --upstream http://127.0.0.1:8000
2019/03/25 19:48:35 Upstream:  => http://127.0.0.1:8000
2019/03/25 19:48:35 connecting to ws://mydomain.com:8000/tunnel with ping=10s
2019/03/25 19:48:35 Ping duration: 10.000000s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6a00b2]

goroutine 1 [running]:
github.com/alexellis/inlets/vendor/github.com/gorilla/websocket.(*Conn).SetReadDeadline(0x0, 0xbf1e668371dfd257, 0x2589597bb, 0xa1f860, 0xbf1e668371dfd257, 0x2589597bb)
	/home/travis/gopath/src/github.com/alexellis/inlets/vendor/github.com/gorilla/websocket/conn.go:1041 +0x22
github.com/alexellis/inlets/pkg/transport.(*WebsocketConn).setupDeadline(0xc420093680)
	/home/travis/gopath/src/github.com/alexellis/inlets/pkg/transport/pingpong.go:37 +0x12e
github.com/alexellis/inlets/pkg/transport.NewWebsocketConn(0x0, 0x2540be400, 0x18)
	/home/travis/gopath/src/github.com/alexellis/inlets/pkg/transport/pingpong.go:23 +0x9c
github.com/alexellis/inlets/pkg/client.(*Client).Connect(0xc4200930b0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/alexellis/inlets/pkg/client/client.go:62 +0x409
github.com/alexellis/inlets/cmd.runClient(0xa1a100, 0xc4200b8300, 0x0, 0x4, 0x0, 0x0)
	/home/travis/gopath/src/github.com/alexellis/inlets/cmd/client.go:99 +0x3bc
github.com/alexellis/inlets/vendor/github.com/spf13/cobra.(*Command).execute(0xa1a100, 0xc4200b8280, 0x4, 0x4, 0xa1a100, 0xc4200b8280)
	/home/travis/gopath/src/github.com/alexellis/inlets/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/alexellis/inlets/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa1a360, 0x7299f7, 0xc420130300, 0x7fca2b)
	/home/travis/gopath/src/github.com/alexellis/inlets/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/alexellis/inlets/vendor/github.com/spf13/cobra.(*Command).Execute(0xa1a360, 0x4042ac, 0xc42008e058)
	/home/travis/gopath/src/github.com/alexellis/inlets/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/alexellis/inlets/cmd.Execute(0x83fdc4, 0x5, 0x845ba0, 0x28, 0xc420057f78, 0xc42008e058)
	/home/travis/gopath/src/github.com/alexellis/inlets/cmd/inlets.go:50 +0x79
main.main()
	/home/travis/gopath/src/github.com/alexellis/inlets/main.go:14 +0x51
```

## Steps to Reproduce (for bugs)

See call above.

## Context
Used the deploy-script with sudo priviledges.

## Your Environment
Linux on both ends. amd64.

**Comment by alexellis** [comment]
Hi @jojomi thanks for your interest.

It looks like you may have a connectivity error as the connection is timing out and the fault is thrown from the underlying library rather than inlets.

What can you tell me about your configuration?

@johnmccabe did you see something similar when writing the Formula for brew?

Alex

**Comment by jojomi** [comment]
I found my error: Remotely I supplied `--token` but I did not locally. When I added the same token when connecting, it worked.

A more helpful error message would have been great!

**Comment by alexellis** [comment]
Thanks for your feedback.

PRs are welcome 😄 

Alex

**Comment by alexellis** [comment]
Derek close

**Comment by johnmccabe** [comment]
@alexellis yeah I'd noticed the crash when tokens mismatched, likewise when the client xant creat it's ephemeral port. Resiliency needs some TLC.

Likewise for the cli, really could do with being able to control the debug output, for example.
